ALTER TABLE [dbo].[expBLCharges]
    ADD CONSTRAINT [PK_empBLDetails] PRIMARY KEY CLUSTERED ([pk_ExpBLChgID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

