ALTER TABLE [dbo].[expBookingCharges]
    ADD CONSTRAINT [PK_expBookingCharges] PRIMARY KEY CLUSTERED ([pk_BookingChgID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

