ALTER TABLE [dbo].[ImpBLFooter]
    ADD CONSTRAINT [PK_ImpBLFooter] PRIMARY KEY CLUSTERED ([pk_BLFooterID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

