ALTER TABLE [dbo].[mstDocCharge]
    ADD CONSTRAINT [PK_mstDocCharge] PRIMARY KEY CLUSTERED ([pk_DocTypeChg] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

