ALTER TABLE [dbo].[mstTerminal]
    ADD CONSTRAINT [PK_mstTerminal] PRIMARY KEY CLUSTERED ([fk_TerminalID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

