ALTER TABLE [dbo].[mstContainerMovOptions]
    ADD CONSTRAINT [PK_mstContainerMovOptions] PRIMARY KEY CLUSTERED ([pk_MovmentOptID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

