ALTER TABLE [dbo].[mstAddress]
    ADD CONSTRAINT [PK_mstVendors] PRIMARY KEY CLUSTERED ([fk_AddressID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

