ALTER TABLE [dbo].[mstContainerType]
    ADD CONSTRAINT [PK_mstContainerType] PRIMARY KEY CLUSTERED ([pk_ContainerTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

