ALTER TABLE [dbo].[mstISO]
    ADD CONSTRAINT [PK_mstISO] PRIMARY KEY CLUSTERED ([pk_ISOID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

