ALTER TABLE [dbo].[trnVessel]
    ADD CONSTRAINT [PK_trn_vessel] PRIMARY KEY CLUSTERED ([fk_CompanyID] ASC, [pk_VesselID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

