ALTER TABLE [dbo].[trnVoyage]
    ADD CONSTRAINT [PK_trn_Voyage] PRIMARY KEY CLUSTERED ([pk_VoyageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

