ALTER TABLE [dbo].[eqpOnHireContainers]
    ADD CONSTRAINT [PK_eqpOnHireDetails] PRIMARY KEY CLUSTERED ([pk_OnHireContainerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

