ALTER TABLE [dbo].[eqpOnHire]
    ADD CONSTRAINT [PK_EqpOnHireContainer] PRIMARY KEY CLUSTERED ([pk_OnHireContID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

