ALTER TABLE [dbo].[eqpContainer]
    ADD CONSTRAINT [PK_eqpContainer] PRIMARY KEY CLUSTERED ([pk_ContainerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

