ALTER TABLE [dbo].[expBLContainer]
    ADD CONSTRAINT [PK_expBLContainer] PRIMARY KEY CLUSTERED ([pk_ExpBLContainerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

