ALTER TABLE [dbo].[finMoneyRcpt]
    ADD CONSTRAINT [PK_finMoneyRcpt] PRIMARY KEY CLUSTERED ([pk_MoneyRcptID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

