ALTER TABLE [dbo].[mstContainerMovement]
    ADD CONSTRAINT [PK_mstContainerMovement] PRIMARY KEY CLUSTERED ([pk_MovementID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

