ALTER TABLE [dbo].[mstCharges]
    ADD CONSTRAINT [PK_mstCharges_1] PRIMARY KEY CLUSTERED ([pk_ChargesID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

