ALTER TABLE [dbo].[mstChargesRate]
    ADD CONSTRAINT [PK_mstChargesRate] PRIMARY KEY CLUSTERED ([pk_ChargesRateID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

