ALTER TABLE [dbo].[mstLastNo]
    ADD CONSTRAINT [PK_mstLastNo] PRIMARY KEY CLUSTERED ([pk_DocNoID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

