ALTER TABLE [dbo].[mstVesselPrefix]
    ADD CONSTRAINT [PK_mstVesselPrefix] PRIMARY KEY CLUSTERED ([fk_VesselPrefixID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

