ALTER TABLE [dbo].[mstCompany]
    ADD CONSTRAINT [PK_mstCompany] PRIMARY KEY CLUSTERED ([pk_CompanyID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

