ALTER TABLE [dbo].[mstFinYear]
    ADD CONSTRAINT [PK_mstFinYear] PRIMARY KEY CLUSTERED ([pk_FinYearID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

