ALTER TABLE [dbo].[mstDocumentType]
    ADD CONSTRAINT [PK_mstInvoiceType] PRIMARY KEY CLUSTERED ([pk_DocTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

