ALTER TABLE [dbo].[mstModules]
    ADD CONSTRAINT [PK_mstModules] PRIMARY KEY CLUSTERED ([pk_Modules] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

