ALTER TABLE [dbo].[mstExportMode]
    ADD CONSTRAINT [PK_mstMode] PRIMARY KEY CLUSTERED ([fk_ModeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

