ALTER TABLE [dbo].[mstUsers]
    ADD CONSTRAINT [PK_mstUser] PRIMARY KEY CLUSTERED ([pk_UserID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

