ALTER TABLE [dbo].[mstRoles]
    ADD CONSTRAINT [PK_mstRoles] PRIMARY KEY CLUSTERED ([pk_RoleID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

