ALTER TABLE [dbo].[eqpContainerOld]
    ADD CONSTRAINT [PK_trnContainer] PRIMARY KEY CLUSTERED ([fk_ContainerID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

