CREATE TABLE [dbo].[expBooking] (
    [pk_BookingID]       BIGINT          NULL,
    [fk_LocationID]      INT             NULL,
    [fk_NVOCCID]         INT             NULL,
    [BookingNo]          VARCHAR (40)    NULL,
    [BookingDate]        DATE            NULL,
    [fk_ExpBLID]         BIGINT          NULL,
    [fk_FinyearID]       INT             NULL,
    [fk_LoadingPortID]   BIGINT          NULL,
    [fk_DestPortID]      BIGINT          NULL,
    [fk_FinalDestID]     BIGINT          NULL,
    [Shipper]            VARCHAR (300)   NULL,
    [Forwarder]          VARCHAR (300)   NULL,
    [Broker]             VARCHAR (300)   NULL,
    [Brokerage]          CHAR (1)        NULL,
    [BrokeragePercent]   DECIMAL (6, 2)  NULL,
    [fk_VesselID]        BIGINT          NULL,
    [fk_VoyageID]        BIGINT          NULL,
    [FeederFreight]      DECIMAL (12, 2) NULL,
    [Slot]               VARCHAR (10)    NULL,
    [fk_MoveOriginalID]  INT             NULL,
    [fk_MoveDestID]      INT             NULL,
    [MainLineVesselPlan] VARCHAR (60)    NULL,
    [MainLiveVoyagePlan] VARCHAR (20)    NULL,
    [ETDTSP]             DATE            NULL,
    [ETAPOD]             DATE            NULL,
    [ETAFinal]           DATE            NULL,
    [FinalML]            VARCHAR (24)    NULL,
    [FinalVoyage]        VARCHAR (10)    NULL,
    [FinalTSP]           DATE            NULL,
    [FinalPOD]           DATE            NULL,
    [FinalFNL]           DATE            NULL,
    [OriginalBLs]        INT             NULL,
    [TotalTEU]           INT             NULL,
    [TotalFEU]           INT             NULL,
    [FreightCorP]        CHAR (1)        NULL,
    [CreditDays]         INT             NULL,
    [Notes]              VARCHAR (300)   NULL,
    [PickNo]             VARCHAR (60)    NULL,
    [BrokeragePerTEU]    DECIMAL (12, 2) NULL,
    [BrokeragePerFEU]    DECIMAL (12, 2) NULL,
    [RefundPerTEU]       DECIMAL (12, 2) NULL,
    [RefundPerFEU]       DECIMAL (12, 2) NULL,
    [AcceptBooking]      BIT             NULL,
    [fk_UserAdded]       INT             NOT NULL,
    [fk_UserLastEdited]  INT             NULL,
    [AddedOn]            DATETIME        NOT NULL,
    [EditedOn]           DATETIME        NULL
);

