CREATE TABLE [dbo].[expBLHeader] (
    [pk_ExpBLID]        BIGINT          NULL,
    [fk_LocationID]     INT             NULL,
    [fk_NVOCCID]        BIGINT          NULL,
    [fk_BookingID]      BIGINT          NULL,
    [ExpBLNo]           VARCHAR (60)    NULL,
    [ExpBLDate]         DATETIME        NULL,
    [fk_PortLoading]    BIGINT          NULL,
    [POLDesc]           VARCHAR (25)    NULL,
    [fk_PortDest]       BIGINT          NULL,
    [PODDesc]           VARCHAR (25)    NULL,
    [fk_FinalDest]      BIGINT          NULL,
    [FinalDesc]         VARCHAR (25)    NULL,
    [fk_PLRecp]         BIGINT          NULL,
    [PLRecpDesc]        VARCHAR (25)    NULL,
    [fk_BLIssue]        BIGINT          NULL,
    [BLIssueDesc]       VARCHAR (25)    NULL,
    [Shipper]           VARCHAR (300)   NULL,
    [Consignee]         VARCHAR (300)   NULL,
    [Notify]            VARCHAR (300)   NULL,
    [Forwarder]         VARCHAR (300)   NULL,
    [Broker]            VARCHAR (300)   NULL,
    [Brokerage]         CHAR (1)        NULL,
    [BrokeragePercent]  DECIMAL (5, 2)  NULL,
    [fk_VesselID]       BIGINT          NULL,
    [fk_VoyageID]       BIGINT          NULL,
    [FeederFreight]     DECIMAL (12, 2) NULL,
    [Slot]              VARCHAR (10)    NULL,
    [MoveOriginal]      VARCHAR (3)     NULL,
    [MoveDest]          VARCHAR (3)     NULL,
    [FinalML]           VARCHAR (3)     NULL,
    [FinalVoyage]       VARCHAR (10)    NULL,
    [FinalTSP]          DATE            NULL,
    [FinalPOD]          DATE            NULL,
    [FinalFNL]          DATE            NULL,
    [NumberofBL]        INT             NULL,
    [TEU]               INT             NULL,
    [FEU]               INT             NULL,
    [FreightPPorCC]     CHAR (1)        NULL,
    [CreditDays]        INT             NULL,
    [Marks]             VARCHAR (300)   NULL,
    [Package]           VARCHAR (300)   NULL,
    [Goods]             VARCHAR (300)   NULL,
    [GrossWeight]       DECIMAL (12, 2) NULL,
    [NetWeight]         DECIMAL (12, 2) NULL,
    [CBM]               DECIMAL (12, 2) NULL,
    [Agent]             VARCHAR (300)   NULL,
    [OriginalBLs]       INT             NULL,
    [Comodity]          VARCHAR (25)    NULL,
    [Hazardous]         BIT             NULL,
    [Technical]         VARCHAR (60)    NULL,
    [UNNo]              VARCHAR (5)     NULL,
    [IMDG]              VARCHAR (4)     NULL,
    [Flash]             VARCHAR (6)     NULL,
    [PackCode]          CHAR (1)        NULL,
    [ShippingBill]      VARCHAR (10)    NULL,
    [ShippingBillDate]  DATE            NULL,
    [PartBL]            CHAR (1)        NULL,
    [fk_UserAdded]      INT             NOT NULL,
    [fk_UserLastEdited] INT             NULL,
    [AddedOn]           DATETIME        NOT NULL,
    [EditedOn]          DATETIME        NULL
);

